server:
  port: 8080
  servlet:
    context-path: /polling
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polling_app
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      dll-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serializzation.WRITE_DATES_AS_TIMESTAMPS: false
    time_zone: UTC
